
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ACTUALNAME BOXOFFICE CELEBRITY CHARNAME LDIR LLANGUAGE LMOVIE LSTORY RUNTIME separatorstart : moviename storyline language director producer writer boxoffice runtime crew \n\t\t\t moviename : LMOVIE \n                 | epsilon storyline : LSTORY \n                 | epsilon language : LLANGUAGE \n                | epsilon director : director dval \n                | dval \n                | epsilon dval : LDIRproducer : lprod producer \n                | lprod \n                | epsilonwriter : separator lwrite writer \n              | lwrite writer\n              | lwrite \n              | epsilon lwrite : CELEBRITYlprod : CELEBRITYboxoffice : BOXOFFICE \n                 | epsilon runtime : RUNTIME \n               | epsilon crew : crew lcast\n            | lcast\n            | epsilon lcast : ACTUALNAME CHARNAME\n             | ACTUALNAME epsilon\n             | epsilon CHARNAME epsilon : '
    
_lr_action_items = {'LMOVIE':([0,],[3,]),'LSTORY':([0,2,3,4,],[-31,6,-2,-3,]),'LLANGUAGE':([0,2,3,4,5,6,7,],[-31,-31,-2,-3,9,-4,-5,]),'LDIR':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,16,],[-31,-31,-2,-3,-31,-4,-5,14,-6,-7,14,-9,-10,-11,-8,]),'CELEBRITY':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,24,25,29,],[-31,-31,-2,-3,-31,-4,-5,-31,-6,-7,19,-9,-10,-11,24,-8,19,-14,-20,24,24,-19,-12,24,]),'separator':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,22,24,25,29,],[-31,-31,-2,-3,-31,-4,-5,-31,-6,-7,-31,-9,-10,-11,21,-8,-13,-14,-20,21,-19,-12,21,]),'BOXOFFICE':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,22,23,24,25,29,30,34,],[-31,-31,-2,-3,-31,-4,-5,-31,-6,-7,-31,-9,-10,-11,-31,-8,-13,-14,-20,27,-17,-18,-19,-12,-31,-16,-15,]),'RUNTIME':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,22,23,24,25,26,27,28,29,30,34,],[-31,-31,-2,-3,-31,-4,-5,-31,-6,-7,-31,-9,-10,-11,-31,-8,-13,-14,-20,-31,-17,-18,-19,-12,32,-21,-22,-31,-16,-15,]),'ACTUALNAME':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,41,42,43,],[-31,-31,-2,-3,-31,-4,-5,-31,-6,-7,-31,-9,-10,-11,-31,-8,-13,-14,-20,-31,-17,-18,-19,-12,-31,-21,-22,-31,-16,38,-23,-24,-15,38,-26,-27,-31,-25,-30,-28,-29,]),'CHARNAME':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,],[-31,-31,-2,-3,-31,-4,-5,-31,-6,-7,-31,-9,-10,-11,-31,-8,-13,-14,-20,-31,-17,-18,-19,-12,-31,-21,-22,-31,-16,-31,-23,-24,-15,-31,-26,41,42,-25,41,-30,-28,-29,]),'$end':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,41,42,43,],[-31,0,-31,-2,-3,-31,-4,-5,-31,-6,-7,-31,-9,-10,-11,-31,-8,-13,-14,-20,-31,-17,-18,-19,-12,-31,-21,-22,-31,-16,-31,-23,-24,-15,-1,-26,-27,-31,-25,-30,-28,-29,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'moviename':([0,],[2,]),'epsilon':([0,2,5,8,11,15,17,20,22,26,29,31,35,38,],[4,7,10,13,18,23,18,28,23,33,23,37,40,43,]),'storyline':([2,],[5,]),'language':([5,],[8,]),'director':([8,],[11,]),'dval':([8,11,],[12,16,]),'producer':([11,17,],[15,25,]),'lprod':([11,17,],[17,17,]),'writer':([15,22,29,],[20,30,34,]),'lwrite':([15,21,22,29,],[22,29,22,22,]),'boxoffice':([20,],[26,]),'runtime':([26,],[31,]),'crew':([31,],[35,]),'lcast':([31,35,],[36,39,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> moviename storyline language director producer writer boxoffice runtime crew','start',9,'p_start','task.py',135),
  ('moviename -> LMOVIE','moviename',1,'p_moviename','task.py',140),
  ('moviename -> epsilon','moviename',1,'p_moviename','task.py',141),
  ('storyline -> LSTORY','storyline',1,'p_storyline','task.py',153),
  ('storyline -> epsilon','storyline',1,'p_storyline','task.py',154),
  ('language -> LLANGUAGE','language',1,'p_language','task.py',165),
  ('language -> epsilon','language',1,'p_language','task.py',166),
  ('director -> director dval','director',2,'p_director','task.py',177),
  ('director -> dval','director',1,'p_director','task.py',178),
  ('director -> epsilon','director',1,'p_director','task.py',179),
  ('dval -> LDIR','dval',1,'p_dval','task.py',185),
  ('producer -> lprod producer','producer',2,'p_producer','task.py',193),
  ('producer -> lprod','producer',1,'p_producer','task.py',194),
  ('producer -> epsilon','producer',1,'p_producer','task.py',195),
  ('writer -> separator lwrite writer','writer',3,'p_writer','task.py',201),
  ('writer -> lwrite writer','writer',2,'p_writer','task.py',202),
  ('writer -> lwrite','writer',1,'p_writer','task.py',203),
  ('writer -> epsilon','writer',1,'p_writer','task.py',204),
  ('lwrite -> CELEBRITY','lwrite',1,'p_lwrite','task.py',209),
  ('lprod -> CELEBRITY','lprod',1,'p_lprod','task.py',217),
  ('boxoffice -> BOXOFFICE','boxoffice',1,'p_boxoffice','task.py',225),
  ('boxoffice -> epsilon','boxoffice',1,'p_boxoffice','task.py',226),
  ('runtime -> RUNTIME','runtime',1,'p_runtime','task.py',238),
  ('runtime -> epsilon','runtime',1,'p_runtime','task.py',239),
  ('crew -> crew lcast','crew',2,'p_crew','task.py',250),
  ('crew -> lcast','crew',1,'p_crew','task.py',251),
  ('crew -> epsilon','crew',1,'p_crew','task.py',252),
  ('lcast -> ACTUALNAME CHARNAME','lcast',2,'p_lcast','task.py',258),
  ('lcast -> ACTUALNAME epsilon','lcast',2,'p_lcast','task.py',259),
  ('lcast -> epsilon CHARNAME','lcast',2,'p_lcast','task.py',260),
  ('epsilon -> <empty>','epsilon',0,'p_epsilon','task.py',269),
]
